### ISSUE TITLE
Folders ended with "." cause error in Windows

### ISSUE THREAD

**Issue by WanHanxi** [UMJI-Advising-Center/DD-Wiki#2]
Cloning this repo in Windows fails with the following messages:
> Cloning into 'D:\UM\0pre-UM\DD-Wiki'...
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 132 (delta 26), reused 47 (delta 9), pack-reused 0
Receiving objects: 100% (132/132), 1.35 MiB | 2.94 MiB/s, done.
Resolving deltas: 100% (26/26), done.
error: invalid path 'xia-yi-zhan/shen-zao/ph.d./README.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

It might work to avoid folders that end with "."

**Comment by TomCC7** [comment]
好像windows不能接受目录以.结尾
> https://www.cnblogs.com/pcheng/p/14211328.html

**Comment by Jiayi-Pan** [comment]
fixed!
